version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 3000
    environment:
      - RAILS_ENV=development
    command: ["sh", "-c", "bundle exec rails db:migrate && ./bin/rails server -b 0.0.0.0"]
    networks:
      - app-network
    
    deploy:
          replicas: 3
          update_config:
            parallelism: 1
            delay: 10s

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge